import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, extname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const webRoot = resolve(projectRoot, "web-dist");
const outputPath = resolve(projectRoot, "dist/cloudflare-inline/worker.mjs");

const contentTypes: Readonly<Record<string, string>> = {
  ".css": "text/css; charset=utf-8",
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
};

const indexHtml = await readFile(resolve(webRoot, "index.html"), "utf8");
const referencedPaths = Array.from(
  indexHtml.matchAll(/(?:href|src)="(\/[^"]+)"/g),
  (match) => match[1],
).filter((path): path is string => Boolean(path));
const assetPaths = Array.from(new Set(["/index.html", ...referencedPaths]));
const entries = await Promise.all(
  assetPaths.map(async (path) => {
    const filePath = resolve(webRoot, `.${path}`);
    if (!filePath.startsWith(`${webRoot}\\`) && filePath !== webRoot) {
      throw new Error(`Asset escapes web root: ${path}`);
    }
    const body = await readFile(filePath, "utf8");
    return [
      path,
      {
        body,
        contentType: contentTypes[extname(path)] ?? "application/octet-stream",
      },
    ] as const;
  }),
);
const embeddedAssets = Object.fromEntries(entries);
embeddedAssets["/"] = embeddedAssets["/index.html"];

const source = `// Generated by scripts/embed-cloudflare-assets.ts. Do not edit.\n` +
  `import worker from "../../src/cloudflare/worker.ts";\n\n` +
  `const assets = ${JSON.stringify(embeddedAssets)};\n` +
  `const indexAsset = assets["/index.html"];\n\n` +
  `const inlineAssets = {\n` +
  `  async fetch(request) {\n` +
  `    const url = new URL(request.url);\n` +
  `    const exact = assets[url.pathname];\n` +
  `    const acceptsHtml = (request.headers.get("accept") ?? "").includes("text/html");\n` +
  `    const asset = exact ?? (acceptsHtml ? indexAsset : undefined);\n` +
  `    if (!asset) return new Response(null, { status: 404 });\n` +
  `    const headers = new Headers({ "content-type": asset.contentType });\n` +
  `    headers.set("cache-control", url.pathname === "/index.html" || !exact\n` +
  `      ? "no-cache"\n` +
  `      : "public, max-age=31536000, immutable");\n` +
  `    return new Response(request.method === "HEAD" ? null : asset.body, { headers });\n` +
  `  },\n` +
  `};\n\n` +
  `export default {\n` +
  `  fetch(request, environment, context) {\n` +
  `    return worker.fetch(request, { ...environment, ASSETS: inlineAssets }, context);\n` +
  `  },\n` +
  `  scheduled(controller, environment, context) {\n` +
  `    return worker.scheduled(controller, environment, context);\n` +
  `  },\n` +
  `};\n`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, source, "utf8");
console.log(`Embedded ${entries.length} web assets in ${outputPath}`);
